apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-clis
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: robgrzelka@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: cert-manager
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux