---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-backend
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress_class }}
    nginx.org/mergeable-ingress-type: "minion"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: {{ .Values.ingress_public_url }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.customer_id }}-{{ .Values.backend_name }}-extnme-svc
          servicePort: 80
        path: "/"

